#ifndef MAEBOT_CHANNELS_H
#define MAEBOT_CHANNELS_H

/////// Data channels //////

#define MAEBOT_STATUS_CHANNEL "MAEBOT_STATUS"
#define MAEBOT_IMU_CHANNEL "MAEBOT_IMU"
#define MAEBOT_ENCODERS_CHANNEL "MAEBOT_ENCODERS"
#define MAEBOT_LINE_SENSORS_CHANNEL "MAEBOT_LINE_SENSORS"
#define MAEBOT_IR_RANGEFINDER_CHANNEL "MAEBOT_IR_RANGEFINDER"
#define RPLIDAR_LASER_CHANNEL "RPLIDAR_LASER"

//////// Additional channels for processes that run on the Maebot -- odometry and motion_controller.
#define ODOMETRY_CHANNEL "ODOMETRY"
#define CONTROLLER_PATH_CHANNEL "CONTROLLER_PATH"

/////// Command channels ///////

#define MAEBOT_MOTOR_COMMAND_CHANNEL "MAEBOT_MOTOR_COMMAND"
#define MAEBOT_LEDS_COMMAND_CHANNEL "MAEBOT_LEDS_COMMAND"
#define MAEBOT_TARGETING_LASER_COMMAND_CHANNEL "MAEBOT_TARGETING_LASER_COMMAND"


#endif // MAEBOT_CHANNELS_H
