#ifndef APPS_SLAM_CHALLENGE_CHANNELS_HPP
#define APPS_SLAM_CHALLENGE_CHANNELS_HPP

#include <string>

const std::string EXPLORATION_CHANNEL("MAEBOT_EXPLORATION_STATUS");
const std::string TEAM_MAP_CHANNEL("MAEBOT_MAP");
const std::string TEAM_POSE_CHANNEL("MAEBOT_POSE");
const std::string STAFF_MAP_CHANNEL("STAFF_MAP");
const std::string STAFF_POSE_CHANNEL("STAFF_POSE");

#endif // APPS_SLAM_CHALLENGE_CHANNELS_HPP
